spring:
  application:
    name: measurement-query-service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8081}
  datasource:
    url: jdbc:postgresql://localhost:5432/measurement-db
    username: measurement
    password: pass123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}

server:
  port: 8084